domain   = 'drlm.org'

nodes = [

# ReaR clients

  { :hostname => 'rear-centos', :fport => 22210 , :ip => '10.100.0.10', :mac => '080027010010', :net => 'vboxnet1', :nic => 2 , :box => 'centos/7', :ram => 256 , :script => 'shell/rear_centos.sh' },
  { :hostname => 'rear-suse', :fport => 22211 , :ip => '10.200.0.11', :mac => '080027010011', :net => 'vboxnet2', :nic => 2 , :box => 'opensuse/openSUSE-42.1-x86_64', :ram => 256 , :script => 'shell/rear_suse.sh' },
  { :hostname => 'rear-ubuntu', :fport => 22212 , :ip => '10.200.0.12', :mac => '080027010012', :net => 'vboxnet2', :nic => 2 , :box => 'ubuntu/xenial64', :ram => 256 , :script => 'shell/rear_ubuntu.sh' },

# DRLM servers

  { :hostname => 'drlm-01', :fport => 22250 , :ip => '10.100.0.50', :mac => '080027010050', :net => 'vboxnet1', :nic =>  2 , :ip2 => '10.200.0.50', :mac2 => '080027020050', :net2 => 'vboxnet2', :nic2 => 3 , :box => 'ubuntu/xenial64', :ram => 512 , :script => 'shell/drlm_ubuntu.sh' },
  { :hostname => 'drlm-02', :fport => 22260 , :ip => '10.100.0.60', :mac => '080027010060', :net => 'vboxnet1', :nic =>  2 , :ip2 => '10.200.0.60', :mac2 => '080027020050', :net2 => 'vboxnet2', :nic2 => 3 , :box => 'ubuntu/xenial64', :ram => 512 , :script => 'shell/drlm_ubuntu.sh' },

]


# Deployment of the Workshop enviroment

Vagrant.configure("2") do |config|
  
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :forwarded_port, guest: 22, host: node[:fport], id: 'ssh' 
      nodeconfig.vm.network "private_network", ip: node[:ip], :mac => node[:mac], :name => node[:net], :adapter => node[:nic]

      if !(node[:ip2].nil?) || !(node[:net2].nil?) || !(node[:nic2].nil?) 
        nodeconfig.vm.network "private_network", ip: node[:ip2], :mac => node[:mac2], :name => node[:net2], :adapter => node[:nic2]
      end

      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
	vb.name = node[:hostname]
      	vb.gui = false
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end
    end
  end

  nodes.each do |node|
  	config.vm.define node[:hostname] do |nodeconfig|
  	  nodeconfig.vm.provision "shell", path: node[:script]
  	end
  end
end


# Problems with vagrant and network config on jessie ...

#  { :hostname => 'rear-debian', :ip => '10.100.0.20', :net => 'vboxnet2', :nic => 2 , :box => 'debian/jessie64', :ram => 256 , :script => 'shell/rear_debian.sh' },
#  { :hostname => 'drlm-debian', :ip => '10.100.0.20', :net => 'vboxnet2', :nic =>  2 , :ip2 => '10.200.0.20', :net2 => 'vboxnet3', :nic2 => 3 , :box => 'debian/jessie64', :ram => 512 , :script => 'shell/drlm_debian.sh' },
